[build]
  command = "echo 'Building NK3IO'"
  publish = "."

[[redirects]]
  from = "/r/*"  # Usa wildcard para cualquier ruta después de /r/
  to = "/redirect.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
