[build]
  command = "echo 'Building NK3IO'"
  publish = "."

[[redirects]]
  from = "/r/:id"  # Captura lo que venga después de /r/ como parámetro :id
  to = "/redirect.html?id=:id"  # Pasa el parámetro a redirect.html
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
