[build]
  command = "echo 'Building NK3IO'"
  publish = "."

[[redirects]]
  from = "/r/*"
  to = "/redirect.html?id=:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
