[build]
  command = "echo 'Building NK3IO'"
  publish = "."

[[redirects]]
  from = "/r"  # Ruta base
  to = "/redirect.html"  # Pasa el parámetro id automáticamente
  status = 200
  force = true  # Obliga a Netlify a respetar los parámetros

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
