[build]
  command = "echo 'Building NK3IO'"
  publish = "."

[[redirects]]
  from = "/r/:id"
  to = "/redirect.html?id=:id"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
